# Generated by Django 2.2.14 on 2020-11-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201128_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref_code',
            new_name='pedidoid',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'primary'), ('M', 'info'), ('R', 'danger')], max_length=1),
        ),
    ]
