# Generated by Django 2.2.14 on 2020-11-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201128_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='productos',
        ),
    ]
