# Generated by Django 2.2.14 on 2020-11-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201128_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='delivery_en_proceso',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='recibido',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refund_granted',
            new_name='reembolsado',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refund_requested',
            new_name='reembolso_requerido',
        ),
    ]
