# Generated by Django 2.2.14 on 2020-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount_price',
            new_name='precio_con_descuento',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tecnología'), ('H', 'Hogar'), ('V', 'Vestimenta')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'Azul'), ('M', 'Morado'), ('R', 'Rojo')], max_length=1),
        ),
    ]
