# Generated by Django 2.2.14 on 2020-11-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201128_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='fecha_de_pedido',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered',
            new_name='realizo_pedido',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='direccion_de_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion_de_envio', to='core.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='direccion_de_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion_de_facturacion', to='core.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='realizo_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
