# Generated by Django 2.2.14 on 2020-11-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201128_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='pago',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_purchasing',
            new_name='compra_habilitada',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dni',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
