# Generated by Django 2.2.14 on 2020-11-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201129_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_type',
            new_name='tipo_de_direccion',
        ),
    ]
