# Generated by Django 2.2.14 on 2020-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201129_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
